project:
  type: website

website:
  title: "mormon metrics"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Blog
    logo: file-bar-graph.svg
  favicon: file-bar-graph.svg
  body-header: |
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  page-footer:
    center: 
      - text: "About Mormon Metrics"
        href: index.qmd
      - text: "Latest Post"
        href: posts/conference_mentions/index.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: false
