project:
  type: website

website:
  title: "mormon metrics"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Blog
    logo: file-bar-graph.svg
  favicon: file-bar-graph.svg
  page-footer:
    center: 
      - text: "About Mormon Metrics"
        href: index.qmd
      - text: "Latest Post"
        href: posts/income_myth/index.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



