project:
  type: website

website:
  title: "mormon metrics"
  navbar:
    left:
      - index.qmd
    logo: file-bar-graph.svg
  favicon: file-bar-graph.svg
  body-header: |
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: cyborg
    css: styles.css
    toc: false
