---
title: Mormon Leavers
date: '2025-02-11'
categories: [Survey Research, Rscript, Link to Dataset]
title-block-banner: false
code-links:
  - text: R Script
    icon: code-slash
    href: https://gist.github.com/acbass49/18994196b58f7476eaed715f28af5ade
  - text: Data
    icon: database
    href: https://www.pewresearch.org/dataset/pew-research-center-2014-u-s-religious-landscape-study/
---

#### Description

The Pew Research Center's 2014 Religious Landscape Study is a comprehensive survey of the religious affiliations, beliefs, and practices of over 35,000 adults in the United States. It found that the Christian share of the population is declining, while the religiously unaffiliated ("nones") are growing. The study also explored the diversity within religious groups, including differences in beliefs and practices.

In my analysis, I filtered this dataset to those who identified as Mormon or grew up Mormon (n=893).

I used this script and data for 3 of a 4-part series... [part2](https://mormonmetrics.substack.com/p/part-2-gender-education-and-leaving), part3, and part4. Part1 I looked at slightly different groups Less active vs. Active vs. Disaffiliated. Whereas part 2,3,and 4, I only looked at those raised in the church who still identify vs don't identify.

On the sidebar, I have provided the following resources:

1. `R Script` - this is a link to an r file that contains the code for my models & the analysis. I left comments explaining the code. You should be able to run through it line-by-line for those interested.
2. `Data` - Access the data by clicking the link on the side. You have to create an account with Pew Research Center if you don't already have one, but they are good about never emailing you.

:::{.callout-note}
Must view this page on desktop - not mobile - to see the links.
:::

For questions and comments, please contact me (see the contact tab of this website for my email)
